name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run install
        run: make deploy && make setup
