name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run install.sh
        run: ./install.sh
