name: macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run uninstall default Homebrew
        run: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

      - name: Run install
        run: make deploy && make setup
